Filter courses based on organization of current sites before serving
edly-io/edx-platform pull request #138
Opened 2020-08-31 13:28 UTC by iam-mhaseeb

**Description**: Filtered courses based on the organization of current sites before serving
**Jira**: https://edlyio.atlassian.net/browse/EDLY-1811

**Testing**:
Login with course_creator role on multiple sites to verify they have courses of their sites only.

2020-08-31 13:43 UTC, rehan99000 reviewed
One query otherwise looks good

2020-08-31 13:43 UTC, rehan99000 commented on openedx/features/edly/utils.py
> +    edly_sub_org = EdlySubOrganization.objects.get(
why make a query if we can get edly sub org by `current_site.edly_sub_org` ?

2020-08-31 13:45 UTC, zubair-arbi requested changes
I have added my feedback.

2020-08-31 13:45 UTC, zubair-arbi commented on openedx/features/edly/utils.py
> +def get_all_courses_based_on_org(request, all_courses):
`filter_courses_based_on_org`

2020-08-31 13:45 UTC, zubair-arbi commented on openedx/features/edly/utils.py
> +    current_site = request.site
```python
edly_user_info_cookie = request.COOKIES.get(settings.EDLY_USER_INFO_COOKIE_NAME, None)
edx_org = get_edx_org_from_cookie(edly_user_info_cookie)

filtered_courses = [course for course in all_courses if course.org == edx_org]
```

2020-08-31 14:48 UTC, zubair-arbi requested changes
Added some more feedback.

2020-08-31 14:48 UTC, zubair-arbi commented on openedx/features/edly/utils.py
> +    Filter courses based on the requested URL site.
nit: new line after first summary line, above `Arguments` and `Returns`.

2020-08-31 14:48 UTC, zubair-arbi commented on openedx/features/edly/tests/test_utils.py
> +        filtered_courses = filter_courses_based_on_org(self.request, courses)
We need to add test:

1. create course with `org_1`
2. create  a new course with `org_2`
3. Verify that total courses count is 2
4. Link and login the user with `org_1`
5. Verify that `filter_courses_based_on_org` method returns only one course
6. Verify that `returned course org == user's linked edx org`

2020-09-01 06:32 UTC, asadmanzoor93 approved these changes

2020-09-01 06:37 UTC, zubair-arbi requested changes
Added more feedback.

2020-09-01 06:37 UTC, zubair-arbi commented on cms/djangoapps/contentstore/views/course.py
> +    all_courses = filter_courses_based_on_org(request, list(all_courses))
we don't need to convert `all_courses` to list here
`all_courses = filter_courses_based_on_org(request, all_courses)`

2020-09-01 06:37 UTC, zubair-arbi commented on openedx/features/edly/tests/test_utils.py
> +        edx_org1 = OrganizationFactory()
`edx_org_1`, `edx_org_2`

2020-09-01 06:37 UTC, zubair-arbi commented on openedx/features/edly/tests/test_utils.py
> +        courses_of_org1 = CourseFactory.create_batch(2, org=edx_org1.short_name)
`courses_of_org_1`

2020-09-01 06:37 UTC, zubair-arbi commented on openedx/features/edly/utils.py
> +    Returns:
nit: new line before `Returns:`

2020-09-01 06:37 UTC, zubair-arbi commented on openedx/features/edly/utils.py
> +        all_courses (list): List of CourseAccessRole objects.
need to update the definition of `all_courses` kwarg

2020-09-01 06:37 UTC, rehan99000 approved these changes

2020-09-01 06:46 UTC, burhandodhy approved these changes

2020-09-01 06:53 UTC, zubair-arbi requested changes
Added 2 more small suggestions.

2020-09-01 06:53 UTC, zubair-arbi commented on openedx/features/edly/tests/test_utils.py
> +from xmodule.modulestore.tests.factories import CourseFactory
nit: alphabatically order the imports

2020-09-01 06:53 UTC, zubair-arbi commented on openedx/features/edly/utils.py
> +    Filter courses based on the requested URL site.
still need to add newline after the first summary line

2020-09-01 07:29 UTC, zubair-arbi commented on openedx/features/edly/tests/test_utils.py
> +from xmodule.modulestore.tests.factories import CourseFactory
Still need to address this.

2020-09-01 07:29 UTC, zubair-arbi commented on openedx/features/edly/tests/test_utils.py
> +from xmodule.modulestore.tests.factories import CourseFactory
https://edx.readthedocs.io/projects/edx-developer-guide/en/latest/style_guides/python-guidelines.html#imports-order

2020-09-01 07:37 UTC, zubair-arbi approved these changes
Changes look good to me now. Please rebase/squash your PR before merging.

2020-09-01 07:45 UTC, merged