added restriction on savinf django settings override save
edly-io/edx-platform pull request #161
Opened 2020-10-27 08:29 UTC by rehan99000

**Description:**
Adds restrictions through clean method of site configuration to make sure only allowed settings are being overridden.

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-2014

![image](https://user-images.githubusercontent.com/20854114/97170427-7f73ab00-17ad-11eb-9fac-f70ddefce751.png)
![image](https://user-images.githubusercontent.com/20854114/97171395-345a9780-17af-11eb-9a3f-29f8c1e7344b.png)

2020-10-27 09:29 UTC, zubair-arbi requested changes
I have added my feedback.

2020-10-27 09:39 UTC, rehan99000 commented on openedx/features/edly/utils.py
> +    disallowed_overrides = list(set(django_settings_overrides_keys) - set(settings.ALLOWED_DJANGO_SETTINGS_OVERRIDE))
done

2020-10-27 09:39 UTC, rehan99000 commented on openedx/features/edly/utils.py
> +    django_settings_overrides_keys = django_settings_overrides.keys()
done

2020-10-27 09:39 UTC, rehan99000 commented on openedx/features/edly/utils.py
> +def clean_django_settings_override(django_settings_overrides):
done

2020-10-27 09:39 UTC, rehan99000 commented on openedx/core/djangoapps/site_configuration/models.py
> +
done

2020-10-27 09:39 UTC, rehan99000 commented on cms/envs/common.py
> +ALLOWED_DJANGO_SETTINGS_OVERRIDE = [
done

2020-10-27 09:56 UTC, zubair-arbi requested changes
Added one more feedback.

2020-10-27 09:56 UTC, zubair-arbi commented on openedx/features/edly/utils.py
> +def clean_django_settings_override(django_settings_override):
Modify this method like following:
```python
def clean_django_settings_override(django_settings_override):
    """
    Enforce only allowed django settings to be overridden.
    """
    if not django_settings_override:
        return

    django_settings_override_keys = django_settings_override.keys()
    disallowed_override_keys = list(set(django_settings_override_keys) - set(settings.ALLOWED_DJANGO_SETTINGS_OVERRIDE))
    updated_override_keys = list(set(django_settings_override_keys) - set(disallowed_override_keys))
    missing_override_keys = list(set(settings.ALLOWED_DJANGO_SETTINGS_OVERRIDE) - set(updated_override_keys))
    
    validation_errors = []
    if disallowed_override_keys:
        disallowed_override_keys_string = ', '.join(disallowed_override_keys)
        validation_errors.append(
            ValidationError(
                _('Django settings override(s) "%(disallowed_overrides)s" is/are not allowed to be overridden.'),
                params={'disallowed_overrides': disallowed_override_keys_string},
            )
        )
        
    if missing_override_keys:
        missing_override_keys_string = ', '.join(missing_override_keys)
        validation_errors.append(
            ValidationError(
                _('Django settings override(s) "%(missing_overrides)s" is/are missing.'),
                params={'missing_overrides': missing_override_keys_string},
            )
        )

    if validation_errors:
        raise ValidationError(validation_errors)
```

2020-10-27 10:43 UTC, rehan99000 commented on openedx/features/edly/utils.py
> +def clean_django_settings_override(django_settings_override):
done

2020-11-02 07:27 UTC, zubair-arbi commented on openedx/features/edly/utils.py
> +                params={'disallowed_overrides': disallowed_override_keys_string},
`disallowed_overrides` -> `disallowed_override_keys`

2020-12-18 09:22 UTC, zubair-arbi approved these changes
Changes looks good 👍 

Please check the client onboarding document one more time and @rehan99000 rebase your branch.

2020-12-29 07:32 UTC, asadmanzoor93 approved these changes

2021-01-01 07:46 UTC, merged