Fix Caption issue with YouTube
edly-io/edx-platform pull request #240
Opened 2021-05-29 10:20 UTC by burhandodhy

**Description:**
This PR fixes the issue where the message `Caption will be displayed when you start playing the video.` shows for the Youtube video even the video doesn't have the caption.

**Jira Ticket**
https://edlyio.atlassian.net/browse/EDLY-3014

**Steps to reproduce** 

1. Add Video module and enable the catpion for the default edX video.
2. Clicked on the `Turn On Caption` button.
3. Add another video module and add any video. 
4. The new video will show `Caption will be displayed when you start playing the video.` message.

2021-05-29 10:53 UTC, iam-mhaseeb approved these changes

2021-05-29 10:55 UTC, taimoor-ahmed-1 approved these changes

2021-05-29 12:35 UTC, zubair-arbi requested changes
Nice fix.

Please add before/after details along with video in PR description. Those videos will be needed on our opensource PR.

2021-05-31 06:58 UTC, burhandodhy commented
> Nice fix.
> 
> Please add before/after details along with video in PR description. Those videos will be needed on our opensource PR.

@zubair-arbi  before and after video added

2021-05-31 07:08 UTC, zubair-arbi approved these changes
@burhandodhy Change looks good 👍 
Thank you for adding videos in PR description.

2021-05-31 07:38 UTC, merged