Makes staff role Edly sub organization based
edly-io/edx-platform pull request #256
Opened 2021-08-10 08:13 UTC by rehan99000

## Description

This PR updates Edly staff role to be Edly suborganization based.

Useful information to include:
- Edly staff user will be impacted

## Supporting information

https://edlyio.atlassian.net/browse/EDLY-3463

## Testing instructions

Please provide detailed step-by-step instructions for testing this change.

## Deadline

By the end of current week

2021-08-12 09:47 UTC, asadmanzoor93 requested changes
Add/update unit tests.

2021-08-12 11:26 UTC, rehan99000 commented
> Add/update unit tests.

This change does not affect any tests

2021-08-12 11:55 UTC, taimoor-ahmed-1 approved these changes

2021-08-13 04:55 UTC, asadmanzoor93 approved these changes

2021-08-13 05:30 UTC, merged