Middleware added to redirect user if site expires
edly-io/edx-platform pull request #336
Opened 2022-11-15 11:07 UTC by marslanabdulrauf

** Description: **
This PR adds a middle to redirect user to pricing page if the trial site expires

**JIRA:** 
https://edlyio.atlassian.net/browse/EDLY-4882

2022-11-15 12:23 UTC, taimoor-ahmed-1 requested changes

2022-11-15 12:23 UTC, taimoor-ahmed-1 commented on openedx/features/edly/utils.py
> +    current_plan = 'essential'  # default value
kindly use constant here for `essentials`

2022-11-15 12:23 UTC, taimoor-ahmed-1 commented on openedx/features/edly/middleware.py
> +def _is_logged_in_path(path):
add docstring

2022-11-15 18:42 UTC, taimoor-ahmed-1 approved these changes

2022-11-15 18:43 UTC, taimoor-ahmed-1 reviewed
A unit test is failing kindly update it.

2022-11-16 08:27 UTC, taimoor-ahmed-1 approved these changes

2022-11-16 09:19 UTC, madnihamza1841 approved these changes
LGTM

2022-11-17 15:33 UTC, merged