Subscription settings added
edly-io/edx-platform pull request #338
Opened 2022-11-23 14:33 UTC by marslanabdulrauf

Description:

This PR adds Subscription Setting for LMS and CMS

JIRA:
https://edlyio.atlassian.net/browse/EDLY-5008

2022-11-24 08:50 UTC, faatehsultan approved these changes

2022-11-29 05:36 UTC, taimoor-ahmed-1 commented on lms/envs/common.py
> +
kindly remove blank line

2022-11-29 06:22 UTC, madnihamza1841 requested changes

2022-11-29 06:22 UTC, madnihamza1841 commented on openedx/features/edly/constants.py
> +COURSE_AUTHERS = 'course_authers'
Kindly correct the spellings for authors.

2022-11-29 06:22 UTC, madnihamza1841 commented on openedx/features/edly/constants.py
> +COURSE_AUTHERS = 'course_authers'
COURSE_AUTHOURS and course_authors

2022-11-29 06:22 UTC, madnihamza1841 commented on lms/envs/common.py
> +        COURSE_AUTHERS: 10,
Correct the spelling here too for COURSE_AUTHOURS

2022-11-29 06:22 UTC, madnihamza1841 commented on lms/envs/common.py
> +        COURSE_AUTHERS: 3,
COURSE_AUTHOURS spelling

2022-11-29 06:22 UTC, madnihamza1841 commented on lms/envs/common.py
> +        COURSE_AUTHERS: 1,
COURSE_AUTHOURS spelling

2022-11-29 06:22 UTC, madnihamza1841 commented on lms/envs/common.py
> +    COURSE_AUTHERS,
Spelling mistake

2022-11-29 13:02 UTC, taimoor-ahmed-1 approved these changes

2022-11-29 13:07 UTC, merged