[Free Trial] Account Limitations for Registered Users and Courses app…
edly-io/edx-platform pull request #340
Opened 2022-11-30 19:21 UTC by madnihamza1841

**Description:**
Account Limitations for plan registered users and total courses were added and applied in LMS and Studio. 
Error messages were also shown.

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-4750

2022-12-01 07:47 UTC, taimoor-ahmed-1 requested changes
Basic idea is to have minimal changes in core apps, please move methods in our custom `openedx/features/edly` app.

2022-12-01 07:47 UTC, taimoor-ahmed-1 commented on cms/djangoapps/contentstore/views/course.py
> +def _courses_limit_reached_for_plan(request):
kindly move method to `edly` app

2022-12-01 07:47 UTC, taimoor-ahmed-1 commented on openedx/core/djangoapps/user_api/accounts/__init__.py
> +PLAN_USER_LIMIT_REACHED_MSG = _(
move to edly constants

2022-12-01 07:47 UTC, taimoor-ahmed-1 commented on openedx/core/djangoapps/user_authn/views/register.py
> +    def _registered_user_limit_reached_for_plan(self, request):
move to `edly` app.

2022-12-01 13:10 UTC, taimoor-ahmed-1 requested changes

2022-12-01 13:10 UTC, taimoor-ahmed-1 commented on openedx/features/edly/validators.py
> +        Checks if the limit for the current site for number of courses is reached.
remove indent

2022-12-01 13:10 UTC, taimoor-ahmed-1 commented on cms/djangoapps/contentstore/views/course.py
>  from openedx.features.edly.utils import filter_courses_based_on_org, get_edx_org_from_cookie, get_enabled_organizations
switch positions of imports

2022-12-01 13:13 UTC, madnihamza1841 commented on openedx/features/edly/validators.py
> +        Checks if the limit for the current site for number of courses is reached.
done

2022-12-01 13:14 UTC, madnihamza1841 commented on cms/djangoapps/contentstore/views/course.py
>  from openedx.features.edly.utils import filter_courses_based_on_org, get_edx_org_from_cookie, get_enabled_organizations
done

2022-12-01 13:15 UTC, taimoor-ahmed-1 approved these changes
LGTM 👍

2022-12-01 14:09 UTC, marslanabdulrauf approved these changes

2022-12-02 05:51 UTC, faatehsultan approved these changes

2022-12-02 06:32 UTC, merged