Adding Usetiful JS code and token for product tours
edly-io/edx-platform pull request #348
Opened 2023-01-04 17:46 UTC by madnihamza1841

**Description:**
Adding the JS code for Usetiful product tours in LMS and CMS base templates.

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-5059

2023-01-05 12:37 UTC, marslanabdulrauf approved these changes

2023-01-06 06:43 UTC, taimoor-ahmed-1 requested changes

2023-01-06 06:43 UTC, taimoor-ahmed-1 commented on lms/envs/common.py
> +
kindly add dummy value here

2023-01-06 08:00 UTC, madnihamza1841 commented on lms/envs/common.py
> +
Done.

2023-01-06 08:03 UTC, muhammadali124 approved these changes

2023-01-10 07:07 UTC, taimoor-ahmed-1 approved these changes

2023-01-11 05:13 UTC, merged