Emails are only sent when they are enabled in site configuraiton
edly-io/edx-platform pull request #358
Opened 2023-02-24 12:06 UTC by marslanabdulrauf

**Description:**

This PR adds and enables email configuration, email are sent if they are enabled by the organization

**JIRA:**
https://edlyio.atlassian.net/browse/EDLY-5185

2023-02-27 10:16 UTC, taimoor-ahmed-1 requested changes

2023-02-27 10:16 UTC, taimoor-ahmed-1 commented on cms/djangoapps/course_creators/admin.py
> +from crum import get_current_request
import sorting

2023-02-27 10:16 UTC, taimoor-ahmed-1 commented on lms/djangoapps/instructor/enrollment.py
> +from crum import get_current_request
import sorting

2023-02-27 10:36 UTC, muhammadali124 approved these changes
LGTM

2023-03-07 09:14 UTC, taimoor-ahmed-1 approved these changes

2023-03-07 10:07 UTC, merged