Feat: Implement password eye icon for reset password screen
edly-io/edx-platform pull request #553
Opened 2024-07-01 06:43 UTC by Anas-hameed

The PR add a password eye Icon on Reset Password Page. 

Jira Ticket:
https://edlyio.atlassian.net/browse/EDLY-6575?atlOrigin=eyJpIjoiODRhZjA4ZWNlOWMxNGI5NWFkY2RhMzYxYTk3Y2NkZjYiLCJwIjoiaiJ9

2024-07-01 07:08 UTC, taimoor-ahmed-1 requested changes

2024-07-01 07:08 UTC, taimoor-ahmed-1 commented on lms/static/js/student_account/components/PasswordResetInput.jsx
> +class PasswordResetInput extends React.Component {
can we override this in edly-edx-themes?

2024-07-03 07:21 UTC, taimoor-ahmed-1 approved these changes

2024-07-03 11:24 UTC, muhammadali124 approved these changes

2024-07-03 11:48 UTC, merged